[package]
name = "tvm_linker"
version = "0.1.0"
authors = ["tonlabs"]

[dependencies]
#base64 = "0.10.0"
byteorder = "1.2.7"
regex = "1"
clap = "2.32"
#crypto-hash = "0.3.1"
ed25519-dalek = "0.9.1"
hex = "0.3.2"
lazy_static = "1.3.0"
log = "0.4.6"
simplelog = "0.5.3"
rand = "0.6.5"
sha2 = "0.8.0"
#jsonrpc-http-server = "10.0.1"

tvm = { path = "../../sdk-emulator/tvm" }
ton_block = { path = "../../sdk-emulator/ton_block" }
